services:
  grace_simple_api.security.authentication.provider:
    class:  Grace\Bundle\ApiBundle\Security\Authentication\Provider\ApiProvider
    arguments: ['', %kernel.cache_dir%/security/nonces]
  grace_simple_api.security.authentication.listener:
    class:  Grace\Bundle\ApiBundle\Security\Firewall\ApiListener
    arguments: [@security.context, @security.authentication.manager, %is_check_ip%, %is_check_token%]
  login_listener:
    class: Grace\Bundle\ApiBundle\Security\LoginListener
    arguments: [@security.context]
    tags:
        - { name: kernel.event_listener, event: security.interactive_login }