<?php

namespace Grace\CGen;

require_once dirname(__FILE__) . '/../../../../src/Grace/CGen/ClassParserAbstract.php';

/**
 * Test class for ClassParserAbstract.
 * Generated by PHPUnit on 2012-04-12 at 13:30:54.
 */
class ClassParserAbstractTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ClassParserAbstract
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ClassParserAbstract;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Grace\CGen\ClassParserAbstract::getOutputDir
     * @todo Implement testGetOutputDir().
     */
    public function testGetOutputDir() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Grace\CGen\ClassParserAbstract::setOutputDir
     * @todo Implement testSetOutputDir().
     */
    public function testSetOutputDir() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Grace\CGen\ClassParserAbstract::getAdditionalClass
     * @todo Implement testGetAdditionalClass().
     */
    public function testGetAdditionalClass() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Grace\CGen\ClassParserAbstract::setAdditionalClass
     * @todo Implement testSetAdditionalClass().
     */
    public function testSetAdditionalClass() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Grace\CGen\ClassParserAbstract::getClassMethods
     * @todo Implement testGetClassMethods().
     */
    public function testGetClassMethods() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Grace\CGen\ClassParserAbstract::getClassName
     * @todo Implement testGetClassName().
     */
    public function testGetClassName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Grace\CGen\ClassParserAbstract::getClassFields
     * @todo Implement testGetClassFields().
     */
    public function testGetClassFields() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Grace\CGen\ClassParserAbstract::getParentClassName
     * @todo Implement testGetParentClassName().
     */
    public function testGetParentClassName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Grace\CGen\ClassParserAbstract::getParentClassMethods
     * @todo Implement testGetParentClassMethods().
     */
    public function testGetParentClassMethods() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Grace\CGen\ClassParserAbstract::getParentClassFields
     * @todo Implement testGetParentClassFields().
     */
    public function testGetParentClassFields() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
