<?php

namespace Grace\CGen;

require_once dirname(__FILE__) . '/../../../../src/Grace/CGen/ClassGeneratorAbstract.php';

/**
 * Test class for ClassGeneratorAbstract.
 * Generated by PHPUnit on 2012-04-12 at 13:14:48.
 */
class ClassGeneratorAbstractTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ClassGeneratorAbstract
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ClassGeneratorAbstract;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Grace\CGen\ClassGeneratorAbstract::getParsedFile
     * @todo Implement testGetParsedFile().
     */
    public function testGetParsedFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Grace\CGen\ClassGeneratorAbstract::setParsedFile
     * @todo Implement testSetParsedFile().
     */
    public function testSetParsedFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Grace\CGen\ClassGeneratorAbstract::getConfig
     * @todo Implement testGetConfig().
     */
    public function testGetConfig() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Grace\CGen\ClassGeneratorAbstract::setConfig
     * @todo Implement testSetConfig().
     */
    public function testSetConfig() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Grace\CGen\ClassGeneratorAbstract::getDirYaml
     * @todo Implement testGetDirYaml().
     */
    public function testGetDirYaml() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Grace\CGen\ClassGeneratorAbstract::getClassesDir
     * @todo Implement testGetClassesDir().
     */
    public function testGetClassesDir() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Grace\CGen\ClassGeneratorAbstract::getClassName
     * @todo Implement testGetClassName().
     */
    public function testGetClassName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Grace\CGen\ClassGeneratorAbstract::getVar
     * @todo Implement testGetVar().
     */
    public function testGetVar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Grace\CGen\ClassGeneratorAbstract::getGetter
     * @todo Implement testGetGetter().
     */
    public function testGetGetter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Grace\CGen\ClassGeneratorAbstract::getSetter
     * @todo Implement testGetSetter().
     */
    public function testGetSetter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
