<?php

namespace Grace\CGen;

require_once dirname(__FILE__) . '/../../../../src/Grace/CGen/DefaultClassGenerator.php';

/**
 * Test class for DefaultClassGenerator.
 * Generated by PHPUnit on 2012-04-12 at 13:34:07.
 */
class DefaultClassGeneratorTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var DefaultClassGenerator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new DefaultClassGenerator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Grace\CGen\DefaultClassGenerator::genYamlClass
     * @todo Implement testGenYamlClass().
     */
    public function testGenYamlClass() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Grace\CGen\DefaultClassGenerator::getVar
     * @todo Implement testGetVar().
     */
    public function testGetVar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Grace\CGen\DefaultClassGenerator::getGetter
     * @todo Implement testGetGetter().
     */
    public function testGetGetter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Grace\CGen\DefaultClassGenerator::getSetter
     * @todo Implement testGetSetter().
     */
    public function testGetSetter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Grace\CGen\DefaultClassGenerator::generate
     * @todo Implement testGenerate().
     */
    public function testGenerate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
