<?php

namespace Grace\CGen;

require_once dirname(__FILE__) . '/../../../../src/Grace/CGen/DefaultYamlParser.php';

/**
 * Test class for DefaultYamlParser.
 * Generated by PHPUnit on 2012-04-12 at 13:34:46.
 */
class DefaultYamlParserTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var DefaultYamlParser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new DefaultYamlParser;
        $symfonyParser = new \Symfony\Component\Yaml\Parser();
        $this->assertEquals($this->object->parser, $symfonyParser);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Grace\CGen\DefaultYamlParser::getParseFile
     * @todo Implement testGetParseFile().
     */
    public function testGetParseFile() {
        // Remove the following lines when you implement this test.
        $exp = array(
            "yaml" => array(
                "fooClass" => array(
                    "implements" => "TestInterface",
                    "fields" => array("fieldName", "fieldName")
                ),
                "barClass" => array(
                    "implements" => "TestingInterface",
                    "fields" => array("fieldFoo", "fieldBar")
                )
            )
        );
        $actual = $this->object->getParseFile(".","YamlTestDefault");
        $this->assertEquals($exp, $actual);
    }

    /**
     * @covers Grace\CGen\DefaultYamlParser::appendToArray
     * @todo Implement testAppendToArray().
     */
    public function testAppendToArray() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Grace\CGen\DefaultYamlParser::getYmlFiles
     * @todo Implement testGetYmlFiles().
     */
    public function testGetYmlFiles() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Grace\CGen\DefaultYamlParser::getChildNodes
     * @todo Implement testGetChildNodes().
     */
    public function testGetChildNodes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
