<?php

namespace Grace\CGen;

require_once dirname(__FILE__) . '/../../../../src/Grace/CGen/DefaultCollectionClassGenerator.php';

/**
 * Test class for DefaultCollectionClassGenerator.
 * Generated by PHPUnit on 2012-04-12 at 13:34:35.
 */
class DefaultCollectionClassGeneratorTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var DefaultCollectionClassGenerator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new DefaultCollectionClassGenerator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Grace\CGen\DefaultCollectionClassGenerator::generate
     * @todo Implement testGenerate().
     */
    public function testGenerate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Grace\CGen\DefaultCollectionClassGenerator::writeClass
     * @todo Implement testWriteClass().
     */
    public function testWriteClass() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Grace\CGen\DefaultCollectionClassGenerator::getClassBody
     * @todo Implement testGetClassBody().
     */
    public function testGetClassBody() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Grace\CGen\DefaultCollectionClassGenerator::getParentClassBody
     * @todo Implement testGetParentClassBody().
     */
    public function testGetParentClassBody() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Grace\CGen\DefaultCollectionClassGenerator::getPreparedData
     * @todo Implement testGetPreparedData().
     */
    public function testGetPreparedData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Grace\CGen\DefaultCollectionClassGenerator::getParentMethodsByMod
     * @todo Implement testGetParentMethodsByMod().
     */
    public function testGetParentMethodsByMod() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Grace\CGen\DefaultCollectionClassGenerator::getItemsByMod
     * @todo Implement testGetItemsByMod().
     */
    public function testGetItemsByMod() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
