<?php

require_once dirname(__FILE__) . '/../../../../src/Grace/CGen/DefaultConcreteClassGenerator.php';

/**
 * Test class for DefaultConcreteClassGenerator.
 * Generated by PHPUnit on 2012-04-12 at 13:34:41.
 */
class DefaultConcreteClassGeneratorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var DefaultConcreteClassGenerator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new DefaultConcreteClassGenerator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers DefaultConcreteClassGenerator::generate
     * @todo Implement testGenerate().
     */
    public function testGenerate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
