<?php

namespace Grace\CGen;

require_once dirname(__FILE__) . '/../../../../src/Grace/CGen/DefaultAbstractClassGenerator.php';

/**
 * Test class for DefaultAbstractClassGenerator.
 * Generated by PHPUnit on 2012-04-12 at 13:32:03.
 */
class DefaultAbstractClassGeneratorTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var DefaultAbstractClassGenerator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new DefaultAbstractClassGenerator(".","./YamlTestDefault","YamlTestDefault");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Grace\CGen\DefaultAbstractClassGenerator::generate
     * @todo Implement testGenerate().
     */
    public function testGenerate() {
        // Remove the following lines when you implement this test.
        
    }

}

?>
