abstract: true
properties:
  id:
    mapping: 'integer'
  name:
    mapping: varchar(255)
  phone:
    mapping: varchar(20)
  password:
    mapping: varchar(255)
    filter: {when: onSet, function: md5}
  token:
    mapping: varchar(255)
  tokenCreatedAt:
    mapping: timestamp
  tokenIp:
    mapping: varchar(255)
  createdAt:
    mapping: timestamp
  lastVisitAt:
    mapping: timestamp
  lastIp:
    mapping: varchar(255)
  countFailedLogins:
    mapping: 'integer'
  isBlocked:
    type: bool
    mapping: 'boolean'
  role:
    mapping: varchar(100)
indexes:
  - 'PRIMARY KEY (`id`)'
  - 'KEY `token` (`token`)'
  - 'KEY `phone` (`phone`)'
