abstract: true
properties:
  id:
    mapping: int
  name:
    mapping: string
  phone:
    mapping: string
  password:
    mapping: string
    filter: {when: onSet, function: md5}
  token:
    mapping: string
  tokenCreatedAt:
    mapping: timestamp
  tokenIp:
    mapping: string
  createdAt:
    mapping: timestamp
  lastVisitAt:
    mapping: timestamp
  lastIp:
    mapping: string
  countFailedLogins:
    mapping: int
  isBlocked:
    mapping: bool
  role:
    mapping: string
